//! The open62541 nodeset compiler's C output, generated from the model rather than the file,
//! and a safe Rust wrapper over it.
//!
//! Mirrors the 1.1 `nodeset_compiler` backend: the primary nodeset compiles into a `.c`/`.h`
//! pair, and every dependency is treated as `--existing` — registered in the `ns[]` array but
//! assumed to already be on the server. Sits outside the `xml` feature so the browser half can
//! compile without the codec.

mod defines;
mod node;
mod order;
mod rust;
mod structured;
mod text;
mod value;

use std::collections::HashSet;

use crate::AddressSpace;

/// What an export downloads: the C pair, the Rust wrapper over its initialiser, and what the
/// compile could not carry over.
#[derive(Clone, Debug)]
pub struct Compiled {
    pub base: String,
    pub header: String,
    pub source: String,
    pub wrapper: String,
    pub nodes: usize,
    pub skipped: usize,
}

/// Compiles the space's primary nodeset the way
/// `nodeset_compiler.py --existing <deps> --xml <primary> <base>` would.
pub fn open62541(
    space: &AddressSpace,
    file_name: &str,
) -> Compiled {
    let base = base_name(file_name);
    let mut printed = HashSet::new();
    let mut functions = String::new();
    let mut nodes = 0usize;
    let mut skipped = 0usize;
    for id in order::sorted(space) {
        match node::compiled_node(space, &id, &base, nodes, &printed) {
            Some(code) => {
                functions.push_str(&code);
                printed.insert(id);
                nodes += 1;
            }
            None => {
                skipped += 1;
                functions.push_str(&format!(
                    "\n/* {id} skipped: open62541 has no C form for GUID or ByteString NodeIds */\n"
                ));
            }
        }
    }
    let source = format!("{}{functions}{}", source_preamble(&base), main_function(space, &base, nodes));
    Compiled {
        header: header_file(space, &base),
        wrapper: rust::wrapper(space, &base),
        source,
        base,
        nodes,
        skipped,
    }
}

/// The C identifier a workspace file name compiles under, which names both files and the
/// initialisation function.
pub fn base_name(file_name: &str) -> String {
    let lower = file_name.to_lowercase();
    let stem = if lower.ends_with(".nodeset2.xml") {
        &file_name[..file_name.len() - ".nodeset2.xml".len()]
    } else if lower.ends_with(".xml") {
        &file_name[..file_name.len() - ".xml".len()]
    } else {
        file_name
    };
    let mut base: String = stem
        .chars()
        .map(|character| match character.is_ascii_alphanumeric() || character == '_' {
            true => character,
            false => '_',
        })
        .collect();
    if base.is_empty() {
        base.push_str("nodeset");
    }
    if base.starts_with(|character: char| character.is_ascii_digit()) {
        base.insert(0, '_');
    }
    base
}

fn header_file(
    space: &AddressSpace,
    base: &str,
) -> String {
    let guard = format!("{}_H_", base.to_uppercase());
    format!(
        "/* WARNING: This is a generated file.\n \
         * Any manual changes will be overwritten. */\n\n\
         #ifndef {guard}\n\
         #define {guard}\n\n\n\
         #ifdef UA_ENABLE_AMALGAMATION\n\
         # include \"open62541.h\"\n\
         #else\n\
         # include <open62541/server.h>\n\
         #endif\n\n\n\
         {}\n\n\
         _UA_BEGIN_DECLS\n\n\
         /* The server's index for each namespace the file lists, filled when {base}() runs. */\n\
         extern UA_UInt16 {base}_ns[{count}];\n\n\
         extern UA_StatusCode {base}(UA_Server *server);\n\n\
         _UA_END_DECLS\n\n\
         #endif /* {guard} */\n",
        defines::section(space, base),
        count = space.namespaces().len()
    )
}

fn source_preamble(base: &str) -> String {
    format!(
        "/* WARNING: This is a generated file.\n \
         * Any manual changes will be overwritten. */\n\n\
         #include \"{base}.h\"\n"
    )
}

/// The extern function: the namespace array, then every begin in order and every finish in
/// reverse, chained so the first failure stops the rest. The array is the exported
/// `<base>_ns`, so the header's `_NODEID` macros and the Rust wrapper read the same mapping.
fn main_function(
    space: &AddressSpace,
    base: &str,
    nodes: usize,
) -> String {
    let count = space.namespaces().len();
    let mut out = format!("\nUA_UInt16 {base}_ns[{count}];\n\nUA_StatusCode {base}(UA_Server *server) {{\n");
    out.push_str("UA_StatusCode retVal = UA_STATUSCODE_GOOD;\n");
    out.push_str("/* Use namespace ids generated by the server */\n");
    out.push_str(&format!("UA_UInt16 *ns = {base}_ns;\n"));
    for index in 0..count {
        let uri = u16::try_from(index)
            .ok()
            .and_then(|index| space.namespaces().uri(index))
            .unwrap_or_default();
        out.push_str(&format!("ns[{index}] = UA_Server_addNamespace(server, {});\n", text::c_string(uri)));
    }
    if nodes > 0 {
        out.push_str("bool dummy = (\n");
        for index in 0..nodes {
            out.push_str(&format!("!(retVal = function_{base}_{index}_begin(server, ns)) &&\n"));
        }
        for index in (0..nodes).rev() {
            let tail = match index {
                0 => " \n",
                _ => " &&\n",
            };
            out.push_str(&format!("!(retVal = function_{base}_{index}_finish(server, ns)){tail}"));
        }
        out.push_str("); (void)(dummy);\n");
    }
    out.push_str("return retVal;\n}\n");
    out
}
